language: generic

install:

  # install plash and dependencies
  - sudo apt-get install python3-pip unionfs-fuse uidmap
  - sudo pip3 install plash

cache:
  directories:
    - ~/plashcache

script:

  - uname -a
  - plash --version

  # load the plash cache
  - sudo tar -xf ~/plashcache/data.tar -C / || sudo plash init
  - plash sudo tar -xf ~/plashcache/userdata.tar -C / || plash init

  - export PLASH_EXPORT='PLASH_INIT_UNION_TASTE'
  - export PLASH_INIT_UNION_TASTE=overlay
  - sudo ./.travis

  # save the plash cache
  - sudo tar -cf ~/plashcache/data.tar /var/lib/plash
  - plash sudo tar -cf ~/plashcache/userdata.tar ~/.plashdata
